name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
        
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

  commit_pdf:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
  
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: PDF
  
      - name: Commit and push PDF
        env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
           USERNAME: ${{ github.repository_owner }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
