name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
        
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

  commit_pdf:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: PDF
  
      - name: Find and unzip the artifact
        run: |
          # Find the zip file in the current directory
          zip_file=$(find . -name '*.zip' | head -n 1)
          if [ -z "$zip_file" ]; then
            echo "No zip file found!"
            exit 1
          else
            echo "Found zip file: $zip_file"
            unzip -o "$zip_file" -d PDF
          fi
  
      - name: Set up Git repository
        uses: actions/checkout@v2
  
      - name: Commit and push PDF
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            mv PDF/main.pdf .
            git add main.pdf
            git commit -m "Add generated PDF"
            git push
